#!/bin/sh

CONFIG_FILE=${CONFIG_FILE:-"/config/config.toml"}
CONFIG_DEFAULT_FILE="/config/config.toml.default"
PERL_CMD="perl -p -i -e"

INFLUXDB_DATA_DIR=${INFLUXDB_DATA_DIR:-"\/data"}
INFLUXDB_REPORTING_DISABLED=${INFLUXDB_REPORTING_DISABLED:-"false"}

INFLUXDB_META_HOSTNAME=${INFLUXDB_META_HOSTNAME:-"localhost"}
INFLUXDB_META_BIND_ADDRESS=${INFLUXDB_META_BIND_ADDRESS:-":8088"}
INFLUXDB_META_RETENTION_AUTO_CREATE=${INFLUXDB_META_RETENTION_AUTO_CREATE:-"true"}
INFLUXDB_META_ELECTION_TIMEOUT=${INFLUXDB_META_ELECTION_TIMEOUT:-"1s"}
INFLUXDB_META_HEARTBEAT_TIMEOUT=${INFLUXDB_META_HEARTBEAT_TIMEOUT:-"1s"}
INFLUXDB_META_LEADER_LEASE_TIMEOUT=${INFLUXDB_META_LEADER_LEASE_TIMEOUT:-"500ms"}
INFLUXDB_META_COMMIT_TIMEOUT=${INFLUXDB_META_COMMIT_TIMEOUT:-"50ms"}

INFLUXDB_DATA_MAX_WAL_SIZE=${INFLUXDB_DATA_MAX_WAL_SIZE:-104857600}
INFLUXDB_DATA_WAL_FLUSH_INTERVAL=${INFLUXDB_DATA_WAL_FLUSH_INTERVAL:-"10m0s"}
INFLUXDB_DATA_WAL_PARTIITON_FLUSH_DELAY=${INFLUXDB_DATA_WAL_PARTIITON_FLUSH_DELAY:-"2s"}
INFLUXDB_DATA_RETENTION_AUTO_CREATE=${INFLUXDB_DATA_RETENTION_AUTO_CREATE:-"true"}
INFLUXDB_DATA_RETENTION_CHECK_ENABLED=${INFLUXDB_DATA_RETENTION_CHECK_ENABLED:-"true"}
INFLUXDB_DATA_RETENTION_CHECK_PERIOD=${INFLUXDB_DATA_RETENTION_CHECK_PERIOD:-"10m0s"}
INFLUXDB_DATA_RETENTION_CREATE_PERIOD=${INFLUXDB_DATA_RETENTION_CREATE_PERIOD:-"45m0s"}

INFLUXDB_CLUSTER_SHARD_WRITER_TIMEOUT=${INFLUXDB_CLUSTER_SHARD_WRITER_TIMEOUT:-"5s"}

INFLUXDB_RETENTION_ENABLED=${INFLUXDB_RETENTION_ENABLED:-"true"}
INFLUXDB_RETENTION_CHECK_INTERVAL=${INFLUXDB_RETENTION_CHECK_INTERVAL:-"10m0s"}

INFLUXDB_SHARD_PRECREATION_ENABLED=${INFLUXDB_SHARD_PRECREATION_ENABLED:-"true"}
INFLUXDB_SHARD_PRECREATION_CHECK_INTERVAL=${INFLUXDB_SHARD_PRECREATION_CHECK_INTERVAL:-"10m0s"}
INFLUXDB_SHARD_PRECREATION_ADVANCE_PERIOD=${INFLUXDB_SHARD_PRECREATION_ADVANCE_PERIOD:-"30m0s"}

INFLUXDB_ADMIN_ENABLED=${INFLUXDB_ADMIN_ENABLED:-"true"}
INFLUXDB_ADMIN_BIND_ADDRESS=${INFLUXDB_ADMIN_BIND_ADDRESS:-":8083"}

INFLUXDB_HTTP_ENABLED=${INFLUXDB_HTTP_ENABLED:-"true"}
INFLUXDB_HTTP_BIND_ADDRESS=${INFLUXDB_HTTP_BIND_ADDRESS:-":8086"}
INFLUXDB_HTTP_AUTH_ENABLED=${INFLUXDB_HTTP_AUTH_ENABLED:-"false"}
INFLUXDB_HTTP_LOG_ENABLED=${INFLUXDB_HTTP_LOG_ENABLED:-"true"}
INFLUXDB_HTTP_WRITE_TRACING=${INFLUXDB_HTTP_WRITE_TRACING:-"false"}
INFLUXDB_HTTP_PPROF_ENABLED=${INFLUXDB_HTTP_PPROF_ENABLED:-"false"}

INFLUXDB_GRAPHITE_BIND_ADDRESS=${INFLUXDB_GRAPHITE_BIND_ADDRESS:-":2003"}
INFLUXDB_GRAPHITE_DATABASE=${INFLUXDB_GRAPHITE_DATABASE:-"graphite"}
INFLUXDB_GRAPHITE_ENABLED=${INFLUXDB_GRAPHITE_ENABLED:-"false"}
INFLUXDB_GRAPHITE_PROTOCOL=${INFLUXDB_GRAPHITE_PROTOCOL:-"tcp"}
INFLUXDB_GRAPHITE_BATCH_SIZE=${INFLUXDB_GRAPHITE_BATCH_SIZE:-"0"}
INFLUXDB_GRAPHITE_BATCH_TIMEOUT=${INFLUXDB_GRAPHITE_BATCH_TIMEOUT:-"0"}
INFLUXDB_GRAPHITE_CONSISTENCY_LEVEL=${INFLUXDB_GRAPHITE_CONSISTENCY_LEVEL:-"one"}
INFLUXDB_GRAPHITE_SEPARATOR=${INFLUXDB_GRAPHITE_SEPARATOR:-"."}

INFLUXDB_COLLECTD_ENABLED=${INFLUXDB_COLLECTD_ENABLED:-"false"}
INFLUXDB_COLLECTD_BIND_ADDRESS=${INFLUXDB_COLLECTD_BIND_ADDRESS:-":25826"}
INFLUXDB_COLLECTD_DATABASE=${INFLUXDB_COLLECTD_DATABASE:-"collectd"}
INFLUXDB_COLLECTD_RETENTION_POLICY=${INFLUXDB_COLLECTD_RETENTION_POLICY:-""}
INFLUXDB_COLLECTD_BATCH_SIZE=${INFLUXDB_COLLECTD_BATCH_SIZE:-"5000"}
INFLUXDB_COLLECTD_BATCH_TIMEOUT=${INFLUXDB_COLLECTD_BATCH_TIMEOUT:-"10s"}
INFLUXDB_COLLECTD_TYPESDB=${INFLUXDB_COLLECTD_TYPESDB:-"\/config\/types.db"}

INFLUXDB_OPENTSDB_ENABLED=${INFLUXDB_OPENTSDB_ENABLED:-"false"}
INFLUXDB_OPENTSDB_BIND_ADDRESS=${INFLUXDB_OPENTSDB_BIND_ADDRESS:-":4242"}
INFLUXDB_OPENTSDB_DATABASE=${INFLUXDB_OPENTSDB_DATABASE:-"opentsdb"}
INFLUXDB_OPENTSDB_RETENTION_POLICY=${INFLUXDB_OPENTSDB_RETENTION_POLICY:-""}
INFLUXDB_OPENTSDB_CONSISTENCY_LEVEL=${INFLUXDB_OPENTSDB_CONSISTENCY_LEVEL:-"one"}

INFLUXDB_UDP_ENABLED=${INFLUXDB_UDP_ENABLED:-"false"}
INFLUXDB_UDP_BIND_ADDRESS=${INFLUXDB_UDP_BIND_ADDRESS:-""}
INFLUXDB_UDP_DATABASE=${INFLUXDB_UDP_DATABASE:-""}
INFLUXDB_UDP_BATCH_SIZE=${INFLUXDB_UDP_BATCH_SIZE:-"0"}
INFLUXDB_UDP_BATCH_TIMEOUT=${INFLUXDB_UDP_BATCH_TIMEOUT:-"0"}

INFLUXDB_MONITORING_ENABLED=${INFLUXDB_MONITORING_ENABLED:-"false"}
INFLUXDB_MONITORING_WRITE_INTERVAL=${INFLUXDB_MONITORING_WRITE_INTERVAL:-"1m0s"}

INFLUXDB_CONTINOUS_QUERIES_ENABLED=${INFLUXDB_CONTINOUS_QUERIES_ENABLED:-"true"}
INFLUXDB_CONTINOUS_RECOMPUTE_PREVIOUS_N=${INFLUXDB_CONTINOUS_RECOMPUTE_PREVIOUS_N:-"2"}
INFLUXDB_CONTINOUS_RECOMPUTE_NO_OLDER_THAN=${INFLUXDB_CONTINOUS_RECOMPUTE_NO_OLDER_THAN:-"10m0s"}
INFLUXDB_CONTINOUS_COMPUTE_RUNS_PER_INTERVAL=${INFLUXDB_CONTINOUS_COMPUTE_RUNS_PER_INTERVAL:-"10"}
INFLUXDB_CONTINOUS_COMPUTE_NO_MORE_THAN=${INFLUXDB_CONTINOUS_COMPUTE_NO_MORE_THAN:-"2m0s"}

INFLUXDB_HINTED_HANDOFF_ENABLED=${INFLUXDB_HINTED_HANDOFF_ENABLED:-"true"}
INFLUXDB_HINTED_HANDOFF_MAX_SIZE=${INFLUXDB_HINTED_HANDOFF_MAX_SIZE:-"1073741824"}
INFLUXDB_HINTED_HANDOFF_MAX_AGE=${INFLUXDB_HINTED_HANDOFF_MAX_AGE:-"168h0m0s"}
INFLUXDB_HINTED_HANDOFF_RETRY_RATE_LIMIT=${INFLUXDB_HINTED_HANDOFF_RETRY_RATE_LIMIT:-"0"}
INFLUXDB_HINTED_HANDOFF_RETRY_INTERVAL=${INFLUXDB_HINTED_HANDOFF_RETRY_INTERVAL:-"1s"}

cp -f /config/config.toml.default ${CONFIG_FILE}

${PERL_CMD} "s/%INFLUXDB_REPORTING_DISABLED%/${INFLUXDB_REPORTING_DISABLED}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_DATA_DIR%/${INFLUXDB_DATA_DIR}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_WAL_DIR%/${INFLUXDB_WAL_DIR}/g" ${CONFIG_FILE}

#META
${PERL_CMD} "s/%INFLUXDB_META_HOSTNAME%/${INFLUXDB_META_HOSTNAME}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_META_BIND_ADDRESS%/${INFLUXDB_META_BIND_ADDRESS}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_META_RETENTION_AUTO_CREATE%/${INFLUXDB_META_RETENTION_AUTO_CREATE}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_META_ELECTION_TIMEOUT%/${INFLUXDB_META_ELECTION_TIMEOUT}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_META_HEARTBEAT_TIMEOUT%/${INFLUXDB_META_HEARTBEAT_TIMEOUT}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_META_LEADER_LEASE_TIMEOUT%/${INFLUXDB_META_LEADER_LEASE_TIMEOUT}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_META_COMMIT_TIMEOUT%/${INFLUXDB_META_COMMIT_TIMEOUT}/g" ${CONFIG_FILE}

#DATA
${PERL_CMD} "s/%INFLUXDB_DATA_MAX_WAL_SIZE%/${INFLUXDB_DATA_MAX_WAL_SIZE}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_DATA_WAL_FLUSH_INTERVAL%/${INFLUXDB_DATA_WAL_FLUSH_INTERVAL}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_DATA_WAL_PARTIITON_FLUSH_DELAY%/${INFLUXDB_DATA_WAL_PARTIITON_FLUSH_DELAY}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_DATA_RETENTION_AUTO_CREATE%/${INFLUXDB_DATA_RETENTION_AUTO_CREATE}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_DATA_RETENTION_CHECK_ENABLED%/${INFLUXDB_DATA_RETENTION_CHECK_ENABLED}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_DATA_RETENTION_CHECK_PERIOD%/${INFLUXDB_DATA_RETENTION_CHECK_PERIOD}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_DATA_RETENTION_CREATE_PERIOD%/${INFLUXDB_DATA_RETENTION_CREATE_PERIOD}/g" ${CONFIG_FILE}

#CLUSTER
${PERL_CMD} "s/%INFLUXDB_CLUSTER_SHARD_WRITER_TIMEOUT%/${INFLUXDB_CLUSTER_SHARD_WRITER_TIMEOUT}/g" ${CONFIG_FILE}

#RETENTION
${PERL_CMD} "s/%INFLUXDB_RETENTION_ENABLED%/${INFLUXDB_RETENTION_ENABLED}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_RETENTION_CHECK_INTERVAL%/${INFLUXDB_RETENTION_CHECK_INTERVAL}/g" ${CONFIG_FILE}

#SHARD
${PERL_CMD} "s/%INFLUXDB_SHARD_PRECREATION_ENABLED%/${INFLUXDB_SHARD_PRECREATION_ENABLED}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_SHARD_PRECREATION_CHECK_INTERVAL%/${INFLUXDB_SHARD_PRECREATION_CHECK_INTERVAL}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_SHARD_PRECREATION_ADVANCE_PERIOD%/${INFLUXDB_SHARD_PRECREATION_ADVANCE_PERIOD}/g" ${CONFIG_FILE}

#ADMIN
${PERL_CMD} "s/%INFLUXDB_ADMIN_ENABLED%/${INFLUXDB_ADMIN_ENABLED}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_ADMIN_BIND_ADDRESS%/${INFLUXDB_ADMIN_BIND_ADDRESS}/g" ${CONFIG_FILE}

#HTTP
${PERL_CMD} "s/%INFLUXDB_HTTP_ENABLED%/${INFLUXDB_HTTP_ENABLED}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_HTTP_BIND_ADDRESS%/${INFLUXDB_HTTP_BIND_ADDRESS}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_HTTP_AUTH_ENABLED%/${INFLUXDB_HTTP_AUTH_ENABLED}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_HTTP_LOG_ENABLED%/${INFLUXDB_HTTP_LOG_ENABLED}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_HTTP_WRITE_TRACING%/${INFLUXDB_HTTP_WRITE_TRACING}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_HTTP_PPROF_ENABLED%/${INFLUXDB_HTTP_PPROF_ENABLED}/g" ${CONFIG_FILE}

#GRAPHITE
${PERL_CMD} "s/%INFLUXDB_GRAPHITE_BIND_ADDRESS%/${INFLUXDB_GRAPHITE_BIND_ADDRESS}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_GRAPHITE_DATABASE%/${INFLUXDB_GRAPHITE_DATABASE}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_GRAPHITE_ENABLED%/${INFLUXDB_GRAPHITE_ENABLED}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_GRAPHITE_PROTOCOL%/${INFLUXDB_GRAPHITE_PROTOCOL}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_GRAPHITE_BATCH_SIZE%/${INFLUXDB_GRAPHITE_BATCH_SIZE}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_GRAPHITE_BATCH_TIMEOUT%/${INFLUXDB_GRAPHITE_BATCH_TIMEOUT}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_GRAPHITE_CONSISTENCY_LEVEL%/${INFLUXDB_GRAPHITE_CONSISTENCY_LEVEL}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_GRAPHITE_SEPARATOR%/${INFLUXDB_GRAPHITE_SEPARATOR}/g" ${CONFIG_FILE}

#COLLECTD
${PERL_CMD} "s/%INFLUXDB_COLLECTD_ENABLED%/${INFLUXDB_COLLECTD_ENABLED}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_COLLECTD_BIND_ADDRESS%/${INFLUXDB_COLLECTD_BIND_ADDRESS}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_COLLECTD_DATABASE%/${INFLUXDB_COLLECTD_DATABASE}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_COLLECTD_RETENTION_POLICY%/${INFLUXDB_COLLECTD_RETENTION_POLICY}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_COLLECTD_BATCH_SIZE%/${INFLUXDB_COLLECTD_BATCH_SIZE}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_COLLECTD_BATCH_TIMEOUT%/${INFLUXDB_COLLECTD_BATCH_TIMEOUT}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_COLLECTD_TYPESDB%/${INFLUXDB_COLLECTD_TYPESDB}/g" ${CONFIG_FILE}

#OPENTSDB
${PERL_CMD} "s/%INFLUXDB_OPENTSDB_ENABLED%/${INFLUXDB_OPENTSDB_ENABLED}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_OPENTSDB_BIND_ADDRESS%/${INFLUXDB_OPENTSDB_BIND_ADDRESS}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_OPENTSDB_DATABASE%/${INFLUXDB_OPENTSDB_DATABASE}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_OPENTSDB_RETENTION_POLICY%/${INFLUXDB_OPENTSDB_RETENTION_POLICY}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_OPENTSDB_CONSISTENCY_LEVEL%/${INFLUXDB_OPENTSDB_CONSISTENCY_LEVEL}/g" ${CONFIG_FILE}

#UDP
${PERL_CMD} "s/%INFLUXDB_UDP_ENABLED%/${INFLUXDB_UDP_ENABLED}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_UDP_BIND_ADDRESS%/${INFLUXDB_UDP_BIND_ADDRESS}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_UDP_DATABASE%/${INFLUXDB_UDP_DATABASE}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_UDP_BATCH_SIZE%/${INFLUXDB_UDP_BATCH_SIZE}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_UDP_BATCH_TIMEOUT%/${INFLUXDB_UDP_BATCH_TIMEOUT}/g" ${CONFIG_FILE}

#MONITORING
${PERL_CMD} "s/%INFLUXDB_MONITORING_ENABLED%/${INFLUXDB_MONITORING_ENABLED}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_MONITORING_WRITE_INTERVAL%/${INFLUXDB_MONITORING_WRITE_INTERVAL}/g" ${CONFIG_FILE}

#CONTINOUS QUERIES
${PERL_CMD} "s/%INFLUXDB_CONTINOUS_QUERIES_ENABLED%/${INFLUXDB_CONTINOUS_QUERIES_ENABLED}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_CONTINOUS_RECOMPUTE_PREVIOUS_N%/${INFLUXDB_CONTINOUS_RECOMPUTE_PREVIOUS_N}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_CONTINOUS_RECOMPUTE_NO_OLDER_THAN%/${INFLUXDB_CONTINOUS_RECOMPUTE_NO_OLDER_THAN}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_CONTINOUS_COMPUTE_RUNS_PER_INTERVAL%/${INFLUXDB_CONTINOUS_COMPUTE_RUNS_PER_INTERVAL}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_CONTINOUS_COMPUTE_NO_MORE_THAN%/${INFLUXDB_CONTINOUS_COMPUTE_NO_MORE_THAN}/g" ${CONFIG_FILE}

#HINTED HANDOFF
${PERL_CMD} "s/%INFLUXDB_HINTED_HANDOFF_ENABLED%/${INFLUXDB_HINTED_HANDOFF_ENABLED}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_HINTED_HANDOFF_MAX_SIZE%/${INFLUXDB_HINTED_HANDOFF_MAX_SIZE}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_HINTED_HANDOFF_MAX_AGE%/${INFLUXDB_HINTED_HANDOFF_MAX_AGE}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_HINTED_HANDOFF_RETRY_RATE_LIMIT%/${INFLUXDB_HINTED_HANDOFF_RETRY_RATE_LIMIT}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_HINTED_HANDOFF_RETRY_INTERVAL%/${INFLUXDB_HINTED_HANDOFF_RETRY_INTERVAL}/g" ${CONFIG_FILE}

/opt/influxdb/influxd -config ${CONFIG_FILE}
